# -*- coding: utf-8 -*-
"""MLlab08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139vEOGPlxhIvGSXB1qNVCNUG4i7PEIA5
"""

from google.colab import files
uploaded = files.upload()

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
# sample_sub = pd.read_csv("sample_submission.csv")

print(train.shape, test.shape)
train.head()

# =========================
# STABLE HIGH-ACCURACY PIPELINE
# =========================

!pip install -q xgboost

import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd # Import pandas if not already imported in this cell scope

# -------------------------
# Feature Engineering (IMPORTANT)
# -------------------------
train["avg_charge"] = train["TotalCharges"] / (train["tenure"] + 1)
test["avg_charge"] = test["TotalCharges"] / (test["tenure"] + 1)

# -------------------------
# Define X and y
# -------------------------
y = train["Churn"]
X = train.drop(columns=["Churn"])

# -------------------------
# Stratified Split
# -------------------------
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# -------------------------
# BETTER XGBOOST (Stable)
# -------------------------
model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

# -------------------------
# Train
# -------------------------
model.fit(X_train, y_train)

# -------------------------
# Evaluate
# -------------------------
y_pred = model.predict(X_val)
print("Validation Accuracy:", accuracy_score(y_val, y_pred))

# -------------------------
# Predict Test
# -------------------------
# Ensure test data has the same columns as training data
# Drop 'Churn' from test before prediction, if it exists (due to align creating it)
if "Churn" in test.columns:
    test_for_prediction = test.drop(columns=["Churn"])
else:
    test_for_prediction = test

test_preds = model.predict(test_for_prediction)

# -------------------------
# Submission
# -------------------------
sample_sub = pd.DataFrame({'id': test['id']})

# IMPORTANT: keep as numeric
sample_sub["Churn"] = test_preds.astype(int)

sample_sub.to_csv("submission.csv", index=False)

print("submission.csv saved!")

